# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.EC2_HOST }}   # 13.234.55.77 jaisa value Secrets → Actions me set karo
          username: ${{ secrets.EC2_USER }}   # ubuntu
          key:      ${{ secrets.EC2_KEY }}    # PEM ka pura text
          port:     22
          script: |
            cd ~/PathakPest
            git pull origin main
            sudo systemctl reload nginx

