name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Skip poore deploy block agar secret blank ho
      - name: End job if EC2_HOST missing
        if: ${{ secrets.EC2_HOST == '' }}
        run: |
          echo "EC2_HOST secret not set — skipping deploy."
          exit 0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        if: ${{ secrets.EC2_HOST != '' }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key:      ${{ secrets.EC2_KEY }}
          port:     22
          script: |
            cd ~/PathakPest
            git pull origin main
            sudo systemctl reload nginx

