name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to 'master' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy over SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          cd /var/www/my-website/PathakPest
          git pull origin main
          sudo systemctl restart nginx

